Add checking number of Ready pods
timoreimann/kubernetes-scripts pull request #2
Opened 2016-09-20 13:31 UTC by wlk

I have added one more step in the `wait-for-deployment` script - checking number of pods that are in `Ready` state, in most cases this step is available right away after "Available replicas" is OK, but there might be other cases (which I don't know yet).

I have also improved log messages that should help with debugging

2016-09-20 15:15 UTC, timoreimann commented
@wlk Thanks for the PR! Checking the pod state definitely sounds worthwhile doing.

I'll try to review your PR until tomorrow.

2016-09-20 20:11 UTC, timoreimann commented
@wlk Looking at my original implementation again, I realize that I check the deployment's status on the [total number of available replicas](https://github.com/timoreimann/kubernetes-scripts/blob/c0bf24dde9a5da6d261daccd494ad018f394d8f7/wait-for-deployment#L29-L31) which is [defined](http://kubernetes.io/docs/api-reference/extensions/v1beta1/definitions/#_v1beta1_deploymentstatus) as the

> Total number of available pods (ready for at least minReadySeconds) targeted by this deployment.

To my understanding, that's equal to the info you'd get from parsing the pod's status conditions. Or am I missing something?

2016-09-21 13:03 UTC, wlk commented
I think we might be checking the same thing but from 2 different angles.
It's hard for me to say exactly but I think there might be cases where those 2 things are not equal.

We use `readinessProbe` and `livenessProbe` (with `initialDelaySeconds`) not `minReadySeconds` when staring pods.

I think it's fine to remove the check I added  (until more information is available)  but keep improved log messages, wdyt?

2016-09-24 11:32 UTC, timoreimann commented on wait-for-deployment
> +echo "Waiting for specified generation: ${generation} for deployment ${deployment} to be observed"
How about having a similar status output as with the generations below; that is, have this line say something like

`Expected generation for deployment ${deployment}: ${generation}`

...

2016-09-24 11:33 UTC, timoreimann commented on wait-for-deployment
> +  echo "Current generation: ${current_generation}, expected generation: ${generation}, waiting"
...and simplify this one to

`Currently observed generation: ${current_generation}`

2016-09-24 11:36 UTC, timoreimann commented on wait-for-deployment
> +echo "Observed expected generation: ${generation}"
`s/${generation}/${current_generation}/` since we use the less-than (`-lt`) operator above now.

2016-09-24 11:37 UTC, timoreimann requested changes
Sorry for the delay -- life's been busy. :-)

I'm fine with dropping the extra readiness check for now but leave the improved logging. I left a few comments in this regard.

2016-10-04 19:14 UTC, wlk commented
I have moved improved logging as part of https://github.com/timoreimann/kubernetes-scripts/pull/4 closing this one

2016-10-04 19:14 UTC, closed without merging